name: Node.js Package

on:
  release:
    types: [created]
  # 建议加上 push 触发，方便你在正式 Release 前测试 build 是否成功
  push:
    branches: [main] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
          fetch-depth: 0

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-dist
          path: dist/  # 这里指向你 build 出来的文件夹
          retention-days: 1 # 自动保留 1 天